# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: volume-1
    vol_size: 100
  - vol_name: volume-2
    vol_size: 100
  - vol_name: volume-3
    vol_size: 100
  - vol_name: volume-4
    vol_size: 100

# Security group
security_groups:
  - name: outside
    description: "Security group for remote ips"
  - name: inside
    description: "Security group for remote groups"

outside_rules:
  - name: outside
    description: "SSH"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: outside
    description: "HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: outside
    description: "Couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: outside
    description: "React app"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

inside_rules:
  - name: inside
    description: "Open all the ports between instances"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_group: inside

# Instance
instances:
  - name: node-1
    volumes: ['volume-1']
    flavor: uom.mse.2c9g
  - name: node-2
    volumes: ['volume-2']
    flavor: uom.mse.2c9g
  - name: node-3
    volumes: ['volume-3']
    flavor: uom.mse.2c9g
  - name: node-4
    volumes: ['volume-4']
    flavor: uom.mse.1c4g

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Test
