- name: Install requirements for pip
  become: yes
  apt:
    name: ['python3-pip','virtualenv','python3-setuptools']
    state: latest
    install_recommends: yes

- name: Install python modules needed for harvester
  become: yes
  pip:
    name: ['couchdb','tweepy']
    state: latest

- name: Push private key to mrc instances
  copy:
    src: ./Test.pem
    dest: /home/ubuntu/.ssh/Test.pem
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '600'

- name: Install open mpi
  become: yes
  apt:
    name: ['openmpi-bin', 'libopenmpi-dev', 'openssh-client']
    state: latest
    install_recommends: yes

- name: Install mpi4py
  become: yes
  pip:
    name: ['mpi4py']
    state: latest
