version: "3"
services:
  couch_master:
    image: "ibmcom/couchdb3:3.0.0"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    links:
      - couch_slave1
      - couch_slave2
      - couch_slave3
    volumes:
      - ./data/master/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.133.178
    container_name: couch_master
    networks:
      couchdb_nw:
        ipv4_address: 172.26.133.178

  couch_slave1:
    image: "ibmcom/couchdb3:3.0.0"
    restart: always
    ports:
      - "15984:5984"
    volumes:
      - ./data/slave1/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.132.153
    container_name: couch_slave1
    networks:
      couchdb_nw:
        ipv4_address: 172.26.132.153

  couch_slave2:
    image: "ibmcom/couchdb3:3.0.0"
    restart: always
    ports:
      - "25984:5984"
    volumes:
      - ./data/slave2/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.128.173
    container_name: couch_slave2
    networks:
      couchdb_nw:
        ipv4_address: 172.26.128.173

  couch_slave3:
    image: "ibmcom/couchdb3:3.0.0"
    restart: always
    ports:
      - "35984:5984"
    volumes:
      - ./data/slave2/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.133.55
    container_name: couch_slave3
    networks:
      couchdb_nw:
        ipv4_address: 172.26.133.55

networks:
  couchdb_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
