- name: Add nodes to CouchDB cluster
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdbusername }}"
    password: "{{ couchdbpassword }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ couchdbusername }}\", \"password\": \"{{ couchdbpassword }}\", \"port\": \"5984\", \"remote_node\": \"{{ inventory_hostname }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ couchdbusername }}\", \"remote_current_password\":\"{{ couchdbpassword }}\"}"

- name: Join nodes to CouchDB cluster
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdbusername }}"
    password: "{{ couchdbpassword }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ inventory_hostname }}\",\"port\":\"5984\",\"username\":\"{{ couchdbusername }}\",\"password\":\"{{ couchdbpassword }}\"}"

- name: Empty request to avoid error messages when finishing cluster setup
  uri:
    url: http://{{ masternode }}:5984/
    method: GET
    user: "{{ couchdbusername }}"
    password: "{{ couchdbpassword }}"
    force_basic_auth: yes
  run_once: true

- name: Finish cluster setup
  uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdbusername }}"
    password: "{{ couchdbpassword }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"
  run_once: true
