- name: Install Dependencies
  tags: always
  become: yes
  apt:
    name: ['docker.io','docker-compose','python3-apt','python-apt','aptitude']
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Create Docker Proxy directory
  tags: always
  become: yes
  file:
    path: "{{ proxy_directory }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Create docker proxy file of environment variables
  tags: 'docker_proxy_file'
  become: yes
  template:
    src: ./http-proxy.conf
    dest: '{{ proxy_path }}'
    owner: '{{ ansible_user }}'
    group: "{{ ansible_user }}"

- name: Daemon and service Reload
  become: yes
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker.service
