- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    #- role: openstack-volume-snapshot

- hosts: COMP90024
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
    - role: couchdb-common
    - role: couchdb-volumes
    - role: couchdb-docker
    - role: couchdb-dockercompose

- hosts: SLAVES
  vars_files:
    - host_vars/couchdb.yaml

  roles:
    - role: couchdb-cluster
