- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack/openstack-common
    - role: openstack/openstack-images
    - role: openstack/openstack-volume
    - role: openstack/openstack-security-group
    - role: openstack/openstack-instance

- hosts: COMP90024
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
    - role: couchdb/couchdb-common
    - role: couchdb/couchdb-volumes
    - role: couchdb/couchdb-docker
    - role: couchdb/couchdb-dockercompose

- hosts: SLAVES
  vars_files:
    - host_vars/couchdb.yaml

  roles:
    - role: couchdb/couchdb-cluster
