# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: WSL-demo-vol-1-1
    vol_size: 10
  - vol_name: WSL-demo-vol-1-2
    vol_size: 10
  - vol_name: WSL-demo-vol-2-1
    vol_size: 10
  - vol_name: WSL-demo-vol-2-2
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: WSL-demo-1
    volumes: ['WSL-demo-vol-1-1', 'WSL-demo-vol-1-2']
  - name: WSL-demo-2
    volumes: ['WSL-demo-vol-2-1', 'WSL-demo-vol-2-2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Assignment2
instance_flavor: uom.mse.2c9g
