# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-1
    vol_size: 120
  - vol_name: demo-vol-2
    vol_size: 120
  - vol_name: demo-vol-3
    vol_size: 120
  - vol_name: demo-vol-4
    vol_size: 120

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Demo security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1']
  - name: demo-2
    volumes: ['demo-vol-2']
  - name: demo-3
    volumes: ['demo-vol-3']
  - name: demo-4
    volumes: ['demo-vol-4']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Test
instance_flavor: uom.mse.1c4g
