# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: volume-1
    vol_size: 120
  - vol_name: volume-2
    vol_size: 120
  - vol_name: volume-3
    vol_size: 120
  - vol_name: volume-4
    vol_size: 120

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Demo security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb_cluster
    description: "Demo security group for couchdb cluster"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb_connection
    description: "Demo security group for couchdb nodes to communicate"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_front_end
    description: "Demo security group for react front end app"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_open_mpi
    description: "open all tcp port for open mpi"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: node-1
    volumes: ['volume-1']
    flavor: uom.mse.2c9g
  - name: node-2
    volumes: ['volume-2']
    flavor: uom.mse.2c9g
  - name: node-3
    volumes: ['volume-3']
    flavor: uom.mse.2c9g
  - name: node-4
    volumes: ['volume-4']
    flavor: uom.mse.1c4g

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Test
