- name: Install npm
  become: yes
  apt:
    name: ['npm']
    state: latest
    install_recommends: yes

- name: Install dependencies and build the app
  become: yes
  command: "{{ item }}"
  args:
    chdir: /home/ubuntu/COMP90024/web-app
  with_items:
    - "npm install"
    - "npm run build"
    - "npm install -g serve"

- name: Launch React app
  become: yes
  command: serve -l 3000 -s build
  async: 600
  poll: 0
  args:
    chdir: /home/ubuntu/COMP90024/web-app
