version: "3"
services:
  docker_couchdb:
    image: "couchdb:latest"
    restart: always
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    environment:
      COUCHDB_USER: "{{ couchdbusername }}"
      COUCHDB_PASSWORD: "{{ couchdbpassword }}"
      NODENAME: "{{ ansible_host }}"
      COUCHDB_SECRET: "{{ couchdbcookie }}"
